/**
 * Task 30E regression tests — image normalization pipeline.
 * Fixtures are REAL decodable rasters generated with sharp at test start
 * (the old fake-byte fixtures asserted the insecure behavior we removed).
 * Assertions inspect decoded output, not byte sizes.
 */
import '../setup'
import { afterAll, beforeAll, beforeEach, describe, expect, test } from 'bun:test'
import { mkdtemp, readFile, readdir, rm } from 'fs/promises'
import { tmpdir } from 'os'
import path from 'path'
import sharp from 'sharp'
import { POST as uploadPOST } from '@/app/api/upload/route'
import { createToken } from '@/lib/auth'
import { normalizeImage } from '@/lib/image-normalize'
import { mockAuth, req } from '../setup'
import { mkUser, wipeDb } from '../fixtures'
import { uploadsDir } from '@/lib/uploads'

let jpegWithExif: Buffer
let plainPng: Buffer
let plainWebp: Buffer
let corruptJpeg: Buffer
let plainSvg: Buffer

beforeAll(async () => {
  // Real raster fixtures generated by the same library version that decodes
  // them in production paths.
  plainPng = await sharp({ create: { width: 40, height: 30, channels: 3, background: { r: 20, g: 160, b: 90 } } })
    .png()
    .toBuffer()
  plainWebp = await sharp({ create: { width: 40, height: 30, channels: 3, background: { r: 10, g: 10, b: 10 } } })
    .webp()
    .toBuffer()
  // JPEG with a REAL EXIF orientation tag (60x40 stored, upright = 40x60)
  // plus a GPS-ish payload — the privacy + rotation case.
  jpegWithExif = await sharp({ create: { width: 60, height: 40, channels: 3, background: { r: 200, g: 30, b: 30 } } })
    .jpeg({ quality: 80 })
    .withMetadata({ orientation: 6 })
    .toBuffer()
  // Append a recognizable EXIF description via a second withMetadata pass is
  // not supported; instead verify stripping by checking the EXIF block and a
  // unique pixel marker. The orientation tag itself is the proof we strip.
  // Valid JPEG magic bytes, then TRUNCATED mid-stream: decoders are lenient
  // about mangled-but-complete streams, but a truncated stream cannot decode.
  corruptJpeg = jpegWithExif.subarray(0, 40)
  // SVG bytes — sharp decodes SVG, the format gate must reject it.
  plainSvg = Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="10" height="10"><rect width="10" height="10"/></svg>')
})

afterAll(async () => {
  await rm(fixtureDirOf(), { recursive: true, force: true })
})

function fixtureDirOf(): string {
  return path.join(tmpdir(), 'ek-img-') // temp dirs cleaned per-run by the runner
}

beforeEach(async () => {
  await wipeDb()
})

describe('normalizeImage (unit)', () => {
  test('accepts real JPEG/PNG/WebP and reports the detected format', async () => {
    for (const [buf, format, ext] of [
      [plainPng, 'png', 'png'],
      [plainWebp, 'webp', 'webp'],
      [jpegWithExif, 'jpeg', 'jpg'],
    ] as const) {
      const n = await normalizeImage(new Uint8Array(buf))
      expect(n.format).toBe(format)
      expect(n.ext).toBe(ext)
      expect(n.bytes.byteLength).toBeGreaterThan(0)
      // Output is itself fully decodable.
      const meta = await sharp(n.bytes).metadata()
      expect(meta.format).toBe(format)
    }
  })

  test('strips EXIF (the GPS/privacy control) — metadata provably absent after', async () => {
    const before = await sharp(jpegWithExif).metadata()
    expect(before.exif).toBeDefined() // fixture really carries an EXIF block
    expect(before.orientation).toBe(6)

    const n = await normalizeImage(new Uint8Array(jpegWithExif))
    const after = await sharp(n.bytes).metadata()
    expect(after.exif).toBeUndefined()
    expect(after.orientation).toBeUndefined()
    // No EXIF APP1 marker survives in the encoded bytes.
    expect(n.bytes.toString('latin1')).not.toContain('Exif\u0000\u0000')
  })

  test('applies EXIF rotation (orientation 6: 60x40 stored → 40x60 upright)', async () => {
    const n = await normalizeImage(new Uint8Array(jpegWithExif))
    expect(n.width).toBe(40)
    expect(n.height).toBe(60)
  })

  test('shrinks oversized images to the 2000px bound without enlarging small ones', async () => {
    const big = await sharp({ create: { width: 3000, height: 1200, channels: 3, background: { r: 0, g: 0, b: 0 } } })
      .png()
      .toBuffer()
    const n = await normalizeImage(new Uint8Array(big))
    expect(n.width).toBe(2000)
    expect(n.height).toBeLessThanOrEqual(2000)

    const small = await normalizeImage(new Uint8Array(plainPng))
    expect(small.width).toBe(40)
    expect(small.height).toBe(30)
  })

  test('rejects non-raster and corrupt payloads', async () => {
    await expect(normalizeImage(new Uint8Array(Buffer.from('totally not an image')))).rejects.toThrow()
    await expect(normalizeImage(new Uint8Array(corruptJpeg))).rejects.toThrow()
    // SVG disguised as anything: sharp decodes it, format gate rejects it.
    await expect(normalizeImage(new Uint8Array(plainSvg))).rejects.toThrow(/unsupported format/)
    // Old-style fixture bytes (PNG magic only) must fail: not a decodable image.
    const fake = new Uint8Array(137)
    fake[0] = 0x89
    await expect(normalizeImage(fake)).rejects.toThrow()
  })
})

describe('POST /api/upload — normalized storage', () => {
  test('stores a real PNG re-encoded by the pipeline, output-derived extension', async () => {
    const user = await mkUser()
    mockAuth(`Bearer ${createToken(user.id)}`)
    const form = new FormData()
    form.append('file', new File([new Uint8Array(plainPng)], 'front.png', { type: 'image/png' }))
    const res = await uploadPOST(req('POST', '/api/upload', form))
    expect(res.status).toBe(200)
    const { url } = (await res.json()) as { url: string }
    expect(url.startsWith('/uploads/')).toBe(true)
    expect(url.endsWith('.png')).toBe(true)

    const onDisk = await readFile(path.join(uploadsDir(), url.replace('/uploads/', '')))
    const meta = await sharp(onDisk).metadata()
    expect(meta.format).toBe('png')
    expect(meta.exif).toBeUndefined()
  })

  test('EXIF-laden JPEG is stored WITHOUT its metadata', async () => {
    const user = await mkUser()
    mockAuth(`Bearer ${createToken(user.id)}`)
    const form = new FormData()
    form.append('file', new File([new Uint8Array(jpegWithExif)], 'label.jpg', { type: 'image/jpeg' }))
    const res = await uploadPOST(req('POST', '/api/upload', form))
    expect(res.status).toBe(200)
    const { url } = (await res.json()) as { url: string }
    const onDisk = await readFile(path.join(uploadsDir(), url.replace('/uploads/', '')))
    const meta = await sharp(onDisk).metadata()
    expect(meta.exif).toBeUndefined()
    expect(meta.orientation).toBeUndefined()
    expect(onDisk.toString('latin1')).not.toContain('Exif\u0000\u0000')
  })

  test('corrupt JPEG with valid magic bytes → 400, nothing persisted', async () => {
    const user = await mkUser()
    mockAuth(`Bearer ${createToken(user.id)}`)
    const dirBefore = new Set(await readdir(uploadsDir()).catch(() => [] as string[]))
    const form = new FormData()
    form.append('file', new File([new Uint8Array(corruptJpeg)], 'broken.jpg', { type: 'image/jpeg' }))
    const res = await uploadPOST(req('POST', '/api/upload', form))
    expect(res.status).toBe(400)
    const dirAfter = new Set(await readdir(uploadsDir()).catch(() => [] as string[]))
    for (const f of dirAfter) {
      if (!dirBefore.has(f)) throw new Error(`file persisted despite failure: ${f}`)
    }
  })

  test('SVG bytes under an image MIME are rejected', async () => {
    const user = await mkUser()
    mockAuth(`Bearer ${createToken(user.id)}`)
    const form = new FormData()
    form.append('file', new File([new Uint8Array(plainSvg)], 'vector.png', { type: 'image/png' }))
    const res = await uploadPOST(req('POST', '/api/upload', form))
    expect(res.status).toBe(400)
  })

  test('old-style fake bytes (PNG magic only) are rejected — decoder not weakened', async () => {
    const user = await mkUser()
    mockAuth(`Bearer ${createToken(user.id)}`)
    const fake = new Uint8Array(137)
    fake[0] = 0x89
    const form = new FormData()
    form.append('file', new File([fake], 'front.png', { type: 'image/png' }))
    const res = await uploadPOST(req('POST', '/api/upload', form))
    expect(res.status).toBe(400)
  })
})
